### ISSUE TITLE
D1 LED getting too much current

### ISSUE THREAD

**Issue by iLoveAndyBaker** [phil-barrett/PicoCNC#4]
Minor nit-pick here, it seems like D1 and D2 are getting too much power (forward voltage is 2.71V), at least compared to the other LEDs on the board.  R1 and R2 are 2.7K, same as the resistor on all the other lines, but it's getting 12V and not 5V/3.3V etc. 

D3 and R49 seem like a much happier combination at the lower voltage, the drop across it while on is 2.53V

**Comment by phil-barrett** [comment]
Thanks for the note.  I believe all the LEDs are quite happy at their current levels.

While D1 and D2 do get more current than D3 and D4, (3.4 mA and 2.3 mA respectively) they are all well below the Max If of 25 mA for the 9-217/GHC-YR1S2/3T LED.  And, all 4 are well below the If they use for the specs (20 mA).  These modern LEDs are amazingly efficient. Back in the bad old days you had to pull 20 mA just to get a dim glow!
![image](https://github.com/phil-barrett/PicoCNC/assets/16570958/1f8beefa-fbeb-45c2-a09d-4d27dc0830df)

I had originally used 680 ohms for D3 and D4 which yields an If of 3.4 mA, I found that 1K gives about the same brightness level. This allows me to reduce the number of unique BOM items. Since I use a lot of 1K resistors, it makes the BOM cost slightly lower. 

There are several other examples of BOM engineering in this board but I will leave it to others to find...
